### ISSUE TITLE
Announcement submission form

### ISSUE THREAD

**Issue by davidwkdavidwk** [goshencollege/gc-communicator#11]
## Describe the required functionality
Any user should be able submit an announcement.  The form should capture
 - Title
 - Category  (selected from a list)
 - A text body
 - A display name for the person posting
 - The date to post the announcement
The current form looks like this but should be re-formatted
![communicator_submit](https://user-images.githubusercontent.com/17414401/119727988-f276fa00-be40-11eb-9fe0-b6e2e9338d7d.PNG)

## Describe alternatives you've considered
None.

## Acceptance Criteria
A user must be able to submit an announcement.  All fields are required

## Dependencies
None

## Required Tests
- Automated tests
  Unit tests should be written which:
  - Successfully submit an announcement
  - Attempt to submit an announcement with missing data
  - Attempt to submit an announcement with a malformed date

## Additional context
The "Related File" field in the screenshot above should be excluded.

**Comment by dboling19** [comment]
Can we get a list of needed categories for the selection menu?

**Comment by dboling19** [comment]
Barebones functionality is completed - will create a different task for adding extra functionality such as categorization, CSS, and repeat announcements.
