### ISSUE TITLE
List a user's announcements

### ISSUE THREAD

**Issue by davidwkdavidwk** [goshencollege/gc-communicator#12]
## Describe the required functionality
A user should be able to view a list of all of the announcements they've submitted.  There should be options for both viewing all and only viewing current and upcoming announcements (ie. excluding past announcements).  There should be a link to clone any announcement and links to edit or delete any upcoming announcement.

## Describe alternatives you've considered
There will be several issues which involve listing announcements in various situations.  It would not be unreasonable to make them all be different filters on the same basic view although there will be minor differences between the different situations.  All future issues involving viewing a list of announcements will link back to this issue in their alternatives section.

## Dependencies
This will require the creation of an Edit page as well.  It should be possible to re-use much of the form from the Add page to accomplish this.  Editing should only be allowed for announcements which are not in the past.

## Required Tests
- Automated tests
  Tests should be written which
  - Submit several test announcements successfully and then check how many announcements are on the view page
  - Submit an additional announcement unsuccessfully and then check how many announcements are on the view page
  - Edit an upcoming announcement
  - Attempt to edit a past announcement

**Comment by dboling19** [comment]
Barebones functionality is completed - Will add more tasks to add functionality, such as modifying announcements, CSS, and archiving announcements.
