### ISSUE TITLE
List all of today's announcements

### ISSUE THREAD

**Issue by davidwkdavidwk** [goshencollege/gc-communicator#13]
## Describe the required functionality
Anyone should be able to view a page which lists the current day's announcements.  The announcements should be grouped by category and there should be a table of contents at the top (also grouped by category) which links to each announcement.  This should look similar to this
![communicator_today](https://user-images.githubusercontent.com/17414401/119731051-767eb100-be44-11eb-9a7f-c87217e849cb.PNG)

## Describe alternatives you've considered
This is an additional list view similar to the one mentioned in #12 .  The big difference here is that:
 - It should list announcements from all users but only ones scheduled to be published on the current date
 - It should *not* allow cloning, editing, or deleting of announcements

## Dependencies
Announcements need to be submitted before this is relevant so it's dependent on #11 

## Required Tests
- Automated tests
  - Several announcements should be submitted for both the current date and future dates.  The number of announcements on this page should match the number submitted for the current date only.
- Manual tests

**Comment by dboling19** [comment]
Barebones functionality is finished - Will make more tasks later for adding features such as Categorization, possibly showing announcements for specified dates, and CSS of course.
