### ISSUE TITLE
Add the ability to categorize announcements

### ISSUE THREAD

**Issue by davidwkdavidwk** [goshencollege/gc-communicator#29]
## Is your feature request related to a problem? Please describe.
There should be a way to add and remove categories.  Each announcement should be assigned to a specific category.  

## Additional context
Removing categories shouldn't actually delete them since that would leave the announcements in that category orphaned.  Instead they should be flagged as inactive and not be an option for new announcements.

**Comment by dboling19** [comment]
Can we get a list of needed categories, at least a few for testing?
I plan on adding a way to easily add more categories and mark them as inactive, I just need to figure out a decent way of keeping that efficeient.

**Comment by davidwkdavidwk** [comment]
Just make some up.  If you want inspiration you can look at a recent communicator but, for now, just create some with random names.

**Comment by dboling19** [comment]
Category functionality implemented into adding new announcements. Will create a new issue for modifiying and adding announcements.
