### ISSUE TITLE
Add the ability to repeat announcements

### ISSUE THREAD

**Issue by davidwkdavidwk** [goshencollege/gc-communicator#31]
## Describe the required functionality
When creating an announcement it must be possible to specify the announcement run on more than one day.

## Describe alternatives you've considered
There are several ways to do this and I'm open to any of them.  The two easiest ones I can think of right now are either specifying a start and end date for the announcement or by specifying a number of distinct dates for the announcement to run.  If you choose the second option you could either create a new `AnnouncementDate` entity so that any announcement can be linked to multiple dates or just create multiple announcements with one of the dates for each.

## Acceptance Criteria
What's required for this to be considered complete?  It may be helpful to frame this as:
- When: A user is creating an announcement.
- Then: They should be able to specify multiple times for the announcement to run.

**Comment by dboling19** [comment]
https://github.com/simshaun/recurr
