### ISSUE TITLE
Hello World!

### ISSUE THREAD

**Issue by davidwkdavidwk** [goshencollege/gc-communicator#6]
## Describe the required functionality
Create a branch.  Create and commit a Hello World! page in that branch.  Create a PR for the branch

## Describe alternatives you've considered
None.

## Acceptance Criteria
None.

## Dependencies
None.

## Required Tests
- Automated unit tests
  - Create a unit test that always succeeds.
- Manual tests
  - Make sure the page loads

## Additional context
None.

**Comment by dboling19** [comment]
File created.
